packages:
  - miniapp
overrides:
  '@dcloudio/uni-cli-shared@3.0.0-alpha-5020120260710001>@intlify/core-base': 9.1.11
  '@dcloudio/uni-cli-shared@3.0.0-alpha-5020120260710001>adm-zip': 0.6.0
  '@dcloudio/uni-mp-weixin@3.0.0-alpha-5020120260710001>ws': 8.21.1
  '@dcloudio/uni-nvue-styler@3.0.0-alpha-5020120260710001>postcss': 8.5.23
  '@intlify/core-base@9.1.11>@intlify/message-resolver': 9.1.11
  '@intlify/message-compiler@9.1.9>@intlify/message-resolver': 9.1.11
  '@intlify/message-compiler@9.1.10>@intlify/message-resolver': 9.1.11
  '@intlify/runtime@9.1.9>@intlify/message-resolver': 9.1.11
  '@intlify/runtime@9.1.10>@intlify/message-resolver': 9.1.11
  '@intlify/vue-devtools@9.1.9>@intlify/message-resolver': 9.1.11
  '@intlify/vue-devtools@9.1.10>@intlify/message-resolver': 9.1.11
  '@jimp/jpeg@0.10.3>jpeg-js': 0.4.4
  vite: 5.4.21
allowBuilds:
  '@parcel/watcher': true
  core-js: true
  core-js-pure: true
  esbuild: true
  vue-demi: true
auditConfig:
  ignoreGhsas:
    - GHSA-fx2h-pf6j-xcff
